language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
# Use clean install to ensure we're getting identical versions to package-lock.json
- npm ci
script:
#  Compile, fail on any error
- tsc
- npm run eslint
